name: Masscan and ShuffleDNS Installation

on: [push]

jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Masscan
      run: |
        git clone https://github.com/blechschmidt/massdns.git
        cd massdns
        make
#        masscan --version

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Install ShuffleDNS
      run: |
        go install -v github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest
        shuffledns -version

    - name: Install DNSGen
      run: |
        python -m pip install dnsgen
        
    - name: Install AltDNS
      run: |
        pip3 install py-altdns==1.0.2        
        
#    - name: Verify installations
#      run: |
#        masscan --version
#        shuffledns -version

#        cat spec_dynamic_words.txt | sort -u > all_words.txt

    - name: executing DNS Brute
      run: |
        cat dynamic_brute_wordlist.txt | sort -u > all_words.txt
        cat all_words.txt | sort -u > temp.tmp
        cat temp.tmp > all_words.txt
        cat target_subdomains.txt | dnsgen -w all_words.txt - | sort -u > /tmp/dnsgen.tmp
        altdns -i target_subdomains.txt -w all_words.txt -o /tmp/altdns.tmp
        cat /tmp/dnsgen.tmp /tmp/altdns.tmp > dnsbrute_wordlist.txt
        cat dnsbrute_wordlist.txt | wc -l
        shuffledns -l dnsbrute_wordlist.txt -d verisign.com -r .resolvers -m massdns/bin/massdns -o output.txt -mode resolve
        
    - name: Upload output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: command-output
        path: output.txt
